#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2013 S. Daniel Francis <francis@sugarlabs.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.

import argparse
import cldevel
import os

actions = {}

parser = argparse.ArgumentParser(description='Colubrid project manager')
subparsers = parser.add_subparsers(dest='action')

for command in cldevel.commands:
    name = command.name
    subparser = subparsers.add_parser(name)
    actions[name] = command.add_args(subparser)

parser.add_argument('-i', '--input', metavar='INPUT', default=os.curdir,
        help='specify the source directory (default: ./)')

args = parser.parse_args()
actions[args.action](args)
